services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ipgeo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    image: meloki/ipgeo-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5069:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=ipgeo;Username=postgres;Password=postgres
      - Jwt__Key=KVywLSwHzzR3eDChb5aekG3Vdad1WRJs8rr7+iygQk0=
      - IpGeoToken=5ed926c882e612
    depends_on:
      db:
        condition: service_healthy
volumes:
  pgdata:
